name: CI
env:
  COREPACK_DEFAULT_TO_LATEST: 0

on:
  pull_request:
  push:
    # branches:
    #   - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup npm
        uses: actions/setup-node@v3
        with:
          node-version: "22"

      - name: Enable corepack
        run: corepack enable
      
      - name: Enable pnpm
        run: corepack use pnpm@9.5.0

      - name: Build
        run: pnpm run build

      - name: Run tests
        run: pnpm run test

      - name: Run linter
        run: pnpm run lint